### ISSUE TITLE
Meditation Trainer: Add loading screen

### ISSUE THREAD

**Issue by ghostfacex** [zendotools/zendo#13]

**Comment by dpurdy** [comment]
![image](https://user-images.githubusercontent.com/332509/83280483-93c66400-a18b-11ea-8a45-273af92bba04.jpeg)

**Comment by dpurdy** [comment]
@ghostfacex : do we want to ask for pwd or code here? I am fine just letting any of our folks into the lab.

**Comment by dpurdy** [comment]
@borissedov : we can pull this info using the Xpring SDK (http://xpring.io), we will just query a specific account(s) to get the balances. You can see an example in node at https://github.com/zendotools/zendoscd

**Comment by dpurdy** [comment]
![IMG_0016](https://user-images.githubusercontent.com/332509/84580686-ef990b80-ad8d-11ea-99bc-2f483dc92d3e.jpeg)
this is how the labs is architected right now. We don't want to ship this at scale this way. :-)

**Comment by dpurdy** [comment]
Decided to make this much simpler if you folks are ok with it.

We are going to pull the lab story and just add this to the mediation trainer.

this will make the whole thing really simple.

two new screens over something that works.

There is the "loading screen" -- where we show the charity info using the Xpring SDK (that code is below) -- 

we use the existing trainer -- @ghostfacex may want to update the content.

add the donation in the trainer (code below)

and then show the results screen on the phone.

const sender = "";
const sponsor = "";
const causePayID = "GiveDirectly$payid.charity"


async function donateXpringSdk()
{
  
  const { Wallet, XRPClient, XRPLNetwork, Utils, TransactionStatus, PayIDClient } = require("xpring-js");

  const payIDClient = new PayIDClient("xrpl-mainnet");

  const XDestination = await payIDClient.addressForPayID(causePayID)

  const grpcURL = "main.xrp.xpring.io:50051"

  const amount = BigInt(166666);

  const wallet = Wallet.generateWalletFromSeed(sponsor);

  const xrpClient = new XRPClient(grpcURL, true)

  xrpClient.network = XRPLNetwork.mainet

  const xSender = Utils.encodeXAddress(sender)

  console.log(xSender)

  const balance = await xrpClient.getBalance(xSender);

  console.log("Sender balance: " + balance)

  console.log(XDestination)

  const destinationBalance = await xrpClient.getBalance(XDestination);

  console.log("Destination balance: " + destinationBalance)
  
  const result = await xrpClient.send(amount, XDestination, wallet)

  console.log("Result: "  + result)

  const status = await xrpClient.getPaymentStatus(result)

  console.log("Status: " + status)

  const success = status == TransactionStatus.Succeeded

  console.log("Sent: " + success)
  
}
