### ISSUE TITLE
Onboarding: Add choose username screen so the user can enter Zendo Labs.

### ISSUE THREAD

**Issue by ghostfacex** [zendotools/zendo#16]
<img width="921" alt="Screenshot 2020-05-25 18 53 39" src="https://user-images.githubusercontent.com/2193704/82852939-1b288480-9eb9-11ea-9d1f-52b0b298aeb3.png">

This means we need to disable the skip feature on the top right. But I think that was a requirement by Apple? Need to discuss.

**Comment by dpurdy** [comment]
My propose here is to make this part of the loading screen on entering the zendo labs story?

As much as possible, was trying to isolate the game components there, so we can rip them out into a new app?

**Comment by dpurdy** [comment]
Going to use the graphic from this, but add it to the zendo labs issue?
