### ISSUE TITLE
iPhone SE2 + 6S support 

### ISSUE THREAD

**Issue by dpurdy** [zendotools/zendo#17]
Resize all of the app elements (specifically in the onboarding, trainer, labs) to work well on small iphones.

**Comment by dpurdy** [comment]
Meditation trainer screen.
Community screen.
New screens.

**Comment by dpurdy** [comment]
![IMG_0007](https://user-images.githubusercontent.com/332509/84580575-f3785e00-ad8c-11ea-831b-579f4cd1015a.jpg)
![IMG_0008](https://user-images.githubusercontent.com/332509/84580576-f4a98b00-ad8c-11ea-9dfc-fe5bf101609f.jpg)
![IMG_0009](https://user-images.githubusercontent.com/332509/84580577-f5dab800-ad8c-11ea-9364-4e6aa44b1185.jpg)
![IMG_0010](https://user-images.githubusercontent.com/332509/84580578-f6734e80-ad8c-11ea-8e5d-f82675b4804f.jpg)

**Comment by dpurdy** [comment]
@borissedov see above.

**Comment by borissedov** [comment]
@dpurdy all done except the last screen. What’s wrong there?

**Comment by dpurdy** [comment]
@ghostfacex : we have a couple of cases where the titles (white) leak into the images (white) on SE2. Want to fix?

**Comment by dpurdy** [comment]
@borissedov : see above

**Comment by dpurdy** [comment]
this is fixed.
