### ISSUE TITLE
Meditation Trainer: Add results screen

### ISSUE THREAD

**Issue by dpurdy** [zendotools/zendo#20]
When the mediation ends show the result pages that we already designed and built.
[Zendo World Flow.pdf](https://github.com/zendotools/zendo/files/4733968/Zendo.World.Flow.pdf)

**Comment by dpurdy** [comment]
@ghostfacex : can you add your mocks here? my napkin drawings are already here.

**Comment by dpurdy** [comment]
think the idea is to have loading screen -- the game screen -- and then the results screen?

**Comment by borissedov** [comment]
@dpurdy so are these screens ready somewhere? Or are we waiting for the UI from @ghostfacex ?

**Comment by dpurdy** [comment]
@ghostfacex  has a mock for this, but I think we are talking about doing all of this on the watch now. Let chat with her.

**Comment by ghostfacex** [comment]
@borissedov this is the result screen. https://www.figma.com/file/KjdCzzAwhqkHKypSBzoiVh/zendo-tools-designs-v5.0?node-id=21%3A1106 
<img width="268" alt="Screenshot 2020-07-05 19 02 13" src="https://user-images.githubusercontent.com/2193704/86548655-0bf21900-bef2-11ea-8e39-cb229bc41ce3.png">

**Comment by borissedov** [comment]
Got it
Looks good
