### ISSUE TITLE
resultsviewcontroller at end of meditation can be wrong

### ISSUE THREAD

**Issue by cancelself** [zendotools/zendo#28]
if there is a long meditation that takes time to sync between the watch + phone, the previous workout is shown.

think the fix is to broadcast the endSession msg from the watch *after* the meditation is saved in healthkit?

**Comment by borissedov** [comment]
@dpurdy can you please let me know how long do I need to meditate and how to stop meditation to reproduce this bug?

**Comment by cancelself** [comment]
Think I figured this out I was poking around the light stuff.
